
project_id = "eaqecvrbzwhdkxnndfkw"

[api]
# Port to start the API proxy server on. Defaults to 54321.
port = 54321
# Extra schemas to expose on your API (besides "public")
schemas = ["storage"]

[functions.save-form-submission]
verify_jwt = false
